export async function generateBriefPdf(
  briefElement: HTMLElement,
  filename: string,
  title: string
): Promise<void> {
  const [{ default: html2canvas }, { default: jsPDF }] = await Promise.all([
    import("html2canvas"),
    import("jspdf"),
  ]);

  // Create a temporary container with forced light mode
  const clone = briefElement.cloneNode(true) as HTMLElement;

  const container = document.createElement("div");
  container.style.position = "absolute";
  container.style.left = "-9999px";
  container.style.top = "0";
  container.style.width = "800px";
  container.style.background = "white";
  container.style.color = "#1a1a1a";
  container.style.padding = "24px";

  // Remove dark mode classes from clone
  clone.querySelectorAll("*").forEach((el) => {
    el.classList.remove("dark");
  });

  // Force all details/collapsible sections open
  clone.querySelectorAll("details").forEach((el) => {
    (el as HTMLDetailsElement).open = true;
  });

  container.appendChild(clone);
  document.body.appendChild(container);

  try {
    const canvas = await html2canvas(container, {
      scale: 2,
      useCORS: true,
      backgroundColor: "#ffffff",
      logging: false,
      windowWidth: 800,
    });

    const pdf = new jsPDF({
      orientation: "portrait",
      unit: "mm",
      format: "a4",
    });

    const pageWidth = 210;
    const pageHeight = 297;
    const margin = 10;
    const contentWidth = pageWidth - 2 * margin;
    const imgWidth = contentWidth;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    // Multi-page: split canvas into page-sized chunks
    let heightLeft = imgHeight;
    let position = margin + 5; // Leave room for header

    // Add header on first page
    pdf.setFontSize(8);
    pdf.setTextColor(150);
    pdf.text("Council \u2014 Strategic Brief", margin, 7);
    pdf.text(title.slice(0, 60), pageWidth - margin, 7, { align: "right" });

    // Add image
    pdf.addImage(canvas.toDataURL("image/png"), "PNG", margin, position, imgWidth, imgHeight, undefined, "FAST");
    heightLeft -= (pageHeight - position - margin);

    while (heightLeft > 0) {
      pdf.addPage();
      position = margin - (imgHeight - heightLeft);
      pdf.addImage(canvas.toDataURL("image/png"), "PNG", margin, position, imgWidth, imgHeight, undefined, "FAST");
      heightLeft -= (pageHeight - 2 * margin);
    }

    // Add footers
    const pageCount = pdf.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      pdf.setPage(i);
      pdf.setFontSize(7);
      pdf.setTextColor(180);
      pdf.text(
        `Page ${i} of ${pageCount} \u00b7 Generated by Council`,
        pageWidth / 2,
        pageHeight - 5,
        { align: "center" }
      );
    }

    pdf.save(filename);
  } finally {
    document.body.removeChild(container);
  }
}
